server:
  port: ${SERVER_PORT}

spring:
  # mail send setting
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_USERNAME} # github ?? ??
    password: ${NAVER_PASSWORD}  # github ?? ??
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  # database setting
  datasource:
    url: ${MARIA_DB_URL}
    username: ${MARIA_DB_USERNAME}
    password: ${MARIA_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # SQL log
    database: mysql

# log level setting
logging:
  level:
    root: info
    com.study.event: debug
    org.hibernate.SQL: debug


jwt:
  secret-key: ${JWT_SECRET}  # ?????? ??????? ??? ??
  access-token-validity-time: 3600000  # 1?? (ms)
  refresh-token-validity-time: 604800000 # 7? (ms)
